# -*- coding: utf-8 -*-
"""Dashboard.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FuIeTz3F8jwnRtzYKiSIJdxuES90c5Ij
"""

import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objs as go 

import pandas as pd
import requests
import json
from pandas.io.json import json_normalize

import streamlit as st

@st.cache(suppress_st_warning=True)
def load_data():
  api_bnpb = "https://opendata.arcgis.com/datasets/685be21cd0034247b5ceeac996d947fe_0.geojson" #initialization of url json
  request = requests.get(api_bnpb)
  data = request.json()
  df = pd.json_normalize(data,'features', sep = "_")
  df.drop(columns = ['type', 'geometry','properties_Object_ID', 'properties_CFR_Harian','properties_RI_Harian','properties_FID','properties_ObjectId'], inplace = True)
  df.rename(columns = {'properties_Provinsi': 'state','properties_Tanggal':'date','properties_Kasus_Terkonfirmasi_Akumulatif': 'Total_Terkonfirmasi', 'properties_Penambahan_Harian_Kasus_Terkonf' : 'Terkonfirmasi_Harian',
                     'properties_Kasus_Sembuh_Akumulatif': 'Total_Sembuh', 'properties_Penambahan_Harian_Kasus_Sembuh': 'Sembuh_Harian', 'properties_Kasus_Meninggal_Akumulatif':'Total_MeninggalDunia','properties_Penambahan_Harian_Kasus_Meningg':'MeninggalDunia_Harian','properties_Kasus_Aktif_Akumulatif':'Total_Aktif' }, inplace=True)
  df.drop(df[df.state=="Indonesia"].index, inplace=True)
  return df
df = load_data()
st.write(df)

st.title('Dashboard Covid-19')
st.markdown('by Nadya Safitri')
'''
Data yang digunakan dalam visualisasi ini adalah data dari BNPB Indonesia dengan url: https://opendata.arcgis.com/datasets/685be21cd0034247b5ceeac996d947fe_0.geojson
'''

'''
Visualisasi data menggunakan Heat Maps
'''
fig = px.choropleth(df, geojson='https://raw.githubusercontent.com/superpikar/indonesia-geojson/master/indonesia.geojson', 
                    locations='state', 
                    color='Total_Terkonfirmasi', 
                    color_continuous_scale='Reds', 
                    featureidkey='properties.state', 
                    animation_frame='date', 
                    range_color=(0, max(df['Total_Terkonfirmasi'])), 
                                        title='Confirmed Cases')
fig.update_layout(margin={"r": 0, "t": 0, "l": 0, "b": 0})
fig.update_geos(fitbounds="locations", visible=False)
st.plotly_chart(fig, use_container_width=True)

